fix(stonedb): error: NoAttrs was not declared in this scope(#146) (#241)
This patch to fix up the compilation error: `NoAttrs` error. and also change `NoObj`, `NoDisplaybleAttrs`
We have changed
`NoAttrs` to `NumOfAttrs` and the files changed in directories as following:
1: stonedb/core
2: stonedb/handler
3: stonedb/loader
4: stonedb/vc

Co-authored-by: mergify[bot] <37929162+mergify[bot]@users.noreply.github.com>